title: 'Cashdesk'
id: 'cashdesk'
currency:
  before:
  after: '€'
  digits: 2
itemsPerRow: 5
categories:
  - name: 'Drinks'
    color: 'blue'
    items:
      - name: 'Coffee'
        price: 1.20
      - name: 'Tea'
        price: 1.20
      - name: 'Softdrinks'
        price: 1.50
      - name: 'Beer'
        price: 2.00
      - name: 'Wine'
        price: 2.50
      - name: 'Longdrinks'
        price: 3.00
  - name: 'Food'
    color: 'red'
    items:
      - name: 'Falafel'
        price: 3.50
      - name: 'Hot Dog'
        price: 3.50
        variants:
          - name: 'with Ketchup'
            color: 'red'
          - name: 'with Mayo'
            color: 'yellow'
      - name: 'Soup'
        price: 3.00
      - name: 'French Fries'
        price: 3.00
        variants:
          - name: 'plain'
            color: 'gray'
            priceDifference: -0.20
          - name: 'with Ketchup'
            color: 'red'
          - name: 'with Mayo'
            priceDifference: 0.20
            color: 'yellow'
      - name: 'Sandwiches'
        price: 4.00
  - name: 'Cake'
    color: 'green'
    items:
      - name: 'Cheesecake'
        price: 1.50
      - name: 'Apple Pie'
        price: 1.50
      - name: 'Chocolate Cake'
        price: 1.50
      - name: 'Lemon Cake'
        price: 1.50
  - name: 'Merchandise'
    color: 'gray'
    items:
      - name: 'Calendar'
        price: 8.00
      - name: 'Postcard'
        price: 1.00
  - name: 'Vouchers'
    items:
      - name: 'Free drink'
        price: 0.00
        color: 'green'
      - name: 'Save 1€'
        price: -1.00
        color: 'blue'
        hideInOrders: true
