
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
* This file exports all enum related types from the schema.
*
* 🟢 You can import this file directly.
*/

export const Color = {
  red: 'red',
  green: 'green',
  blue: 'blue',
  yellow: 'yellow',
  purple: 'purple',
  orange: 'orange',
  pink: 'pink',
  teal: 'teal',
  rose: 'rose',
  taupe: 'taupe'
} as const

export type Color = (typeof Color)[keyof typeof Color]


export const PaymentStatus = {
  waitingForTerminal: 'waitingForTerminal',
  inProcess: 'inProcess',
  pending: 'pending',
  completed: 'completed',
  failed: 'failed',
  cancelled: 'cancelled',
  error: 'error'
} as const

export type PaymentStatus = (typeof PaymentStatus)[keyof typeof PaymentStatus]
