
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the browser.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/index-browser"

export type * from '../models.ts'
export type * from './prismaNamespace.ts'

export const Decimal = runtime.Decimal


export const NullTypes = {
  DbNull: runtime.NullTypes.DbNull as (new (secret: never) => typeof runtime.DbNull),
  JsonNull: runtime.NullTypes.JsonNull as (new (secret: never) => typeof runtime.JsonNull),
  AnyNull: runtime.NullTypes.AnyNull as (new (secret: never) => typeof runtime.AnyNull),
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.DbNull

/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.JsonNull

/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.AnyNull


export const ModelName = {
  Category: 'Category',
  Product: 'Product',
  Variant: 'Variant',
  FloatingOrder: 'FloatingOrder',
  Order: 'Order',
  OrderItem: 'OrderItem',
  SumUpPayment: 'SumUpPayment'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]

/*
 * Enums
 */

export const TransactionIsolationLevel = runtime.makeStrictEnum({
  Serializable: 'Serializable'
} as const)

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]


export const CategoryScalarFieldEnum = {
  id: 'id',
  order: 'order',
  name: 'name',
  color: 'color',
  isArchived: 'isArchived'
} as const

export type CategoryScalarFieldEnum = (typeof CategoryScalarFieldEnum)[keyof typeof CategoryScalarFieldEnum]


export const ProductScalarFieldEnum = {
  id: 'id',
  categoryId: 'categoryId',
  order: 'order',
  name: 'name',
  price: 'price',
  color: 'color',
  hideInOrders: 'hideInOrders',
  variantNameOverridesName: 'variantNameOverridesName',
  isArchived: 'isArchived'
} as const

export type ProductScalarFieldEnum = (typeof ProductScalarFieldEnum)[keyof typeof ProductScalarFieldEnum]


export const VariantScalarFieldEnum = {
  id: 'id',
  productId: 'productId',
  order: 'order',
  name: 'name',
  priceDifference: 'priceDifference',
  color: 'color',
  isArchived: 'isArchived'
} as const

export type VariantScalarFieldEnum = (typeof VariantScalarFieldEnum)[keyof typeof VariantScalarFieldEnum]


export const FloatingOrderScalarFieldEnum = {
  id: 'id',
  lastKeepAlive: 'lastKeepAlive'
} as const

export type FloatingOrderScalarFieldEnum = (typeof FloatingOrderScalarFieldEnum)[keyof typeof FloatingOrderScalarFieldEnum]


export const OrderScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  finishedAt: 'finishedAt',
  totalPrice: 'totalPrice',
  paymentMethod: 'paymentMethod'
} as const

export type OrderScalarFieldEnum = (typeof OrderScalarFieldEnum)[keyof typeof OrderScalarFieldEnum]


export const OrderItemScalarFieldEnum = {
  id: 'id',
  floatingOrderId: 'floatingOrderId',
  orderId: 'orderId',
  productId: 'productId',
  variantId: 'variantId',
  amount: 'amount',
  done: 'done'
} as const

export type OrderItemScalarFieldEnum = (typeof OrderItemScalarFieldEnum)[keyof typeof OrderItemScalarFieldEnum]


export const SumUpPaymentScalarFieldEnum = {
  id: 'id',
  paymentId: 'paymentId',
  status: 'status',
  amount: 'amount',
  orderId: 'orderId'
} as const

export type SumUpPaymentScalarFieldEnum = (typeof SumUpPaymentScalarFieldEnum)[keyof typeof SumUpPaymentScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const NullsOrder = {
  first: 'first',
  last: 'last'
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]

