
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `FloatingOrder` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model FloatingOrder
 * 
 */
export type FloatingOrderModel = runtime.Types.Result.DefaultSelection<Prisma.$FloatingOrderPayload>

export type AggregateFloatingOrder = {
  _count: FloatingOrderCountAggregateOutputType | null
  _avg: FloatingOrderAvgAggregateOutputType | null
  _sum: FloatingOrderSumAggregateOutputType | null
  _min: FloatingOrderMinAggregateOutputType | null
  _max: FloatingOrderMaxAggregateOutputType | null
}

export type FloatingOrderAvgAggregateOutputType = {
  id: number | null
}

export type FloatingOrderSumAggregateOutputType = {
  id: number | null
}

export type FloatingOrderMinAggregateOutputType = {
  id: number | null
  lastKeepAlive: Date | null
}

export type FloatingOrderMaxAggregateOutputType = {
  id: number | null
  lastKeepAlive: Date | null
}

export type FloatingOrderCountAggregateOutputType = {
  id: number
  lastKeepAlive: number
  _all: number
}


export type FloatingOrderAvgAggregateInputType = {
  id?: true
}

export type FloatingOrderSumAggregateInputType = {
  id?: true
}

export type FloatingOrderMinAggregateInputType = {
  id?: true
  lastKeepAlive?: true
}

export type FloatingOrderMaxAggregateInputType = {
  id?: true
  lastKeepAlive?: true
}

export type FloatingOrderCountAggregateInputType = {
  id?: true
  lastKeepAlive?: true
  _all?: true
}

export type FloatingOrderAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which FloatingOrder to aggregate.
   */
  where?: Prisma.FloatingOrderWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of FloatingOrders to fetch.
   */
  orderBy?: Prisma.FloatingOrderOrderByWithRelationInput | Prisma.FloatingOrderOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.FloatingOrderWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` FloatingOrders from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` FloatingOrders.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned FloatingOrders
  **/
  _count?: true | FloatingOrderCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: FloatingOrderAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: FloatingOrderSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: FloatingOrderMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: FloatingOrderMaxAggregateInputType
}

export type GetFloatingOrderAggregateType<T extends FloatingOrderAggregateArgs> = {
      [P in keyof T & keyof AggregateFloatingOrder]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateFloatingOrder[P]>
    : Prisma.GetScalarType<T[P], AggregateFloatingOrder[P]>
}




export type FloatingOrderGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.FloatingOrderWhereInput
  orderBy?: Prisma.FloatingOrderOrderByWithAggregationInput | Prisma.FloatingOrderOrderByWithAggregationInput[]
  by: Prisma.FloatingOrderScalarFieldEnum[] | Prisma.FloatingOrderScalarFieldEnum
  having?: Prisma.FloatingOrderScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: FloatingOrderCountAggregateInputType | true
  _avg?: FloatingOrderAvgAggregateInputType
  _sum?: FloatingOrderSumAggregateInputType
  _min?: FloatingOrderMinAggregateInputType
  _max?: FloatingOrderMaxAggregateInputType
}

export type FloatingOrderGroupByOutputType = {
  id: number
  lastKeepAlive: Date
  _count: FloatingOrderCountAggregateOutputType | null
  _avg: FloatingOrderAvgAggregateOutputType | null
  _sum: FloatingOrderSumAggregateOutputType | null
  _min: FloatingOrderMinAggregateOutputType | null
  _max: FloatingOrderMaxAggregateOutputType | null
}

export type GetFloatingOrderGroupByPayload<T extends FloatingOrderGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<FloatingOrderGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof FloatingOrderGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], FloatingOrderGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], FloatingOrderGroupByOutputType[P]>
      }
    >
  >



export type FloatingOrderWhereInput = {
  AND?: Prisma.FloatingOrderWhereInput | Prisma.FloatingOrderWhereInput[]
  OR?: Prisma.FloatingOrderWhereInput[]
  NOT?: Prisma.FloatingOrderWhereInput | Prisma.FloatingOrderWhereInput[]
  id?: Prisma.IntFilter<"FloatingOrder"> | number
  lastKeepAlive?: Prisma.DateTimeFilter<"FloatingOrder"> | Date | string
  items?: Prisma.OrderItemListRelationFilter
}

export type FloatingOrderOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  lastKeepAlive?: Prisma.SortOrder
  items?: Prisma.OrderItemOrderByRelationAggregateInput
}

export type FloatingOrderWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  AND?: Prisma.FloatingOrderWhereInput | Prisma.FloatingOrderWhereInput[]
  OR?: Prisma.FloatingOrderWhereInput[]
  NOT?: Prisma.FloatingOrderWhereInput | Prisma.FloatingOrderWhereInput[]
  lastKeepAlive?: Prisma.DateTimeFilter<"FloatingOrder"> | Date | string
  items?: Prisma.OrderItemListRelationFilter
}, "id">

export type FloatingOrderOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  lastKeepAlive?: Prisma.SortOrder
  _count?: Prisma.FloatingOrderCountOrderByAggregateInput
  _avg?: Prisma.FloatingOrderAvgOrderByAggregateInput
  _max?: Prisma.FloatingOrderMaxOrderByAggregateInput
  _min?: Prisma.FloatingOrderMinOrderByAggregateInput
  _sum?: Prisma.FloatingOrderSumOrderByAggregateInput
}

export type FloatingOrderScalarWhereWithAggregatesInput = {
  AND?: Prisma.FloatingOrderScalarWhereWithAggregatesInput | Prisma.FloatingOrderScalarWhereWithAggregatesInput[]
  OR?: Prisma.FloatingOrderScalarWhereWithAggregatesInput[]
  NOT?: Prisma.FloatingOrderScalarWhereWithAggregatesInput | Prisma.FloatingOrderScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"FloatingOrder"> | number
  lastKeepAlive?: Prisma.DateTimeWithAggregatesFilter<"FloatingOrder"> | Date | string
}

export type FloatingOrderCreateInput = {
  lastKeepAlive?: Date | string
  items?: Prisma.OrderItemCreateNestedManyWithoutFloatingOrderInput
}

export type FloatingOrderUncheckedCreateInput = {
  id?: number
  lastKeepAlive?: Date | string
  items?: Prisma.OrderItemUncheckedCreateNestedManyWithoutFloatingOrderInput
}

export type FloatingOrderUpdateInput = {
  lastKeepAlive?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  items?: Prisma.OrderItemUpdateManyWithoutFloatingOrderNestedInput
}

export type FloatingOrderUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  lastKeepAlive?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  items?: Prisma.OrderItemUncheckedUpdateManyWithoutFloatingOrderNestedInput
}

export type FloatingOrderCreateManyInput = {
  id?: number
  lastKeepAlive?: Date | string
}

export type FloatingOrderUpdateManyMutationInput = {
  lastKeepAlive?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type FloatingOrderUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  lastKeepAlive?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type FloatingOrderCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  lastKeepAlive?: Prisma.SortOrder
}

export type FloatingOrderAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
}

export type FloatingOrderMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  lastKeepAlive?: Prisma.SortOrder
}

export type FloatingOrderMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  lastKeepAlive?: Prisma.SortOrder
}

export type FloatingOrderSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
}

export type FloatingOrderNullableScalarRelationFilter = {
  is?: Prisma.FloatingOrderWhereInput | null
  isNot?: Prisma.FloatingOrderWhereInput | null
}

export type DateTimeFieldUpdateOperationsInput = {
  set?: Date | string
}

export type FloatingOrderCreateNestedOneWithoutItemsInput = {
  create?: Prisma.XOR<Prisma.FloatingOrderCreateWithoutItemsInput, Prisma.FloatingOrderUncheckedCreateWithoutItemsInput>
  connectOrCreate?: Prisma.FloatingOrderCreateOrConnectWithoutItemsInput
  connect?: Prisma.FloatingOrderWhereUniqueInput
}

export type FloatingOrderUpdateOneWithoutItemsNestedInput = {
  create?: Prisma.XOR<Prisma.FloatingOrderCreateWithoutItemsInput, Prisma.FloatingOrderUncheckedCreateWithoutItemsInput>
  connectOrCreate?: Prisma.FloatingOrderCreateOrConnectWithoutItemsInput
  upsert?: Prisma.FloatingOrderUpsertWithoutItemsInput
  disconnect?: Prisma.FloatingOrderWhereInput | boolean
  delete?: Prisma.FloatingOrderWhereInput | boolean
  connect?: Prisma.FloatingOrderWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.FloatingOrderUpdateToOneWithWhereWithoutItemsInput, Prisma.FloatingOrderUpdateWithoutItemsInput>, Prisma.FloatingOrderUncheckedUpdateWithoutItemsInput>
}

export type FloatingOrderCreateWithoutItemsInput = {
  lastKeepAlive?: Date | string
}

export type FloatingOrderUncheckedCreateWithoutItemsInput = {
  id?: number
  lastKeepAlive?: Date | string
}

export type FloatingOrderCreateOrConnectWithoutItemsInput = {
  where: Prisma.FloatingOrderWhereUniqueInput
  create: Prisma.XOR<Prisma.FloatingOrderCreateWithoutItemsInput, Prisma.FloatingOrderUncheckedCreateWithoutItemsInput>
}

export type FloatingOrderUpsertWithoutItemsInput = {
  update: Prisma.XOR<Prisma.FloatingOrderUpdateWithoutItemsInput, Prisma.FloatingOrderUncheckedUpdateWithoutItemsInput>
  create: Prisma.XOR<Prisma.FloatingOrderCreateWithoutItemsInput, Prisma.FloatingOrderUncheckedCreateWithoutItemsInput>
  where?: Prisma.FloatingOrderWhereInput
}

export type FloatingOrderUpdateToOneWithWhereWithoutItemsInput = {
  where?: Prisma.FloatingOrderWhereInput
  data: Prisma.XOR<Prisma.FloatingOrderUpdateWithoutItemsInput, Prisma.FloatingOrderUncheckedUpdateWithoutItemsInput>
}

export type FloatingOrderUpdateWithoutItemsInput = {
  lastKeepAlive?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type FloatingOrderUncheckedUpdateWithoutItemsInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  lastKeepAlive?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}


/**
 * Count Type FloatingOrderCountOutputType
 */

export type FloatingOrderCountOutputType = {
  items: number
}

export type FloatingOrderCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  items?: boolean | FloatingOrderCountOutputTypeCountItemsArgs
}

/**
 * FloatingOrderCountOutputType without action
 */
export type FloatingOrderCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FloatingOrderCountOutputType
   */
  select?: Prisma.FloatingOrderCountOutputTypeSelect<ExtArgs> | null
}

/**
 * FloatingOrderCountOutputType without action
 */
export type FloatingOrderCountOutputTypeCountItemsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.OrderItemWhereInput
}


export type FloatingOrderSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  lastKeepAlive?: boolean
  items?: boolean | Prisma.FloatingOrder$itemsArgs<ExtArgs>
  _count?: boolean | Prisma.FloatingOrderCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["floatingOrder"]>

export type FloatingOrderSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  lastKeepAlive?: boolean
}, ExtArgs["result"]["floatingOrder"]>

export type FloatingOrderSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  lastKeepAlive?: boolean
}, ExtArgs["result"]["floatingOrder"]>

export type FloatingOrderSelectScalar = {
  id?: boolean
  lastKeepAlive?: boolean
}

export type FloatingOrderOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "lastKeepAlive", ExtArgs["result"]["floatingOrder"]>
export type FloatingOrderInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  items?: boolean | Prisma.FloatingOrder$itemsArgs<ExtArgs>
  _count?: boolean | Prisma.FloatingOrderCountOutputTypeDefaultArgs<ExtArgs>
}
export type FloatingOrderIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}
export type FloatingOrderIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}

export type $FloatingOrderPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "FloatingOrder"
  objects: {
    items: Prisma.$OrderItemPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    lastKeepAlive: Date
  }, ExtArgs["result"]["floatingOrder"]>
  composites: {}
}

export type FloatingOrderGetPayload<S extends boolean | null | undefined | FloatingOrderDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$FloatingOrderPayload, S>

export type FloatingOrderCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<FloatingOrderFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: FloatingOrderCountAggregateInputType | true
  }

export interface FloatingOrderDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['FloatingOrder'], meta: { name: 'FloatingOrder' } }
  /**
   * Find zero or one FloatingOrder that matches the filter.
   * @param {FloatingOrderFindUniqueArgs} args - Arguments to find a FloatingOrder
   * @example
   * // Get one FloatingOrder
   * const floatingOrder = await prisma.floatingOrder.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends FloatingOrderFindUniqueArgs>(args: Prisma.SelectSubset<T, FloatingOrderFindUniqueArgs<ExtArgs>>): Prisma.Prisma__FloatingOrderClient<runtime.Types.Result.GetResult<Prisma.$FloatingOrderPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one FloatingOrder that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {FloatingOrderFindUniqueOrThrowArgs} args - Arguments to find a FloatingOrder
   * @example
   * // Get one FloatingOrder
   * const floatingOrder = await prisma.floatingOrder.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends FloatingOrderFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, FloatingOrderFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__FloatingOrderClient<runtime.Types.Result.GetResult<Prisma.$FloatingOrderPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first FloatingOrder that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FloatingOrderFindFirstArgs} args - Arguments to find a FloatingOrder
   * @example
   * // Get one FloatingOrder
   * const floatingOrder = await prisma.floatingOrder.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends FloatingOrderFindFirstArgs>(args?: Prisma.SelectSubset<T, FloatingOrderFindFirstArgs<ExtArgs>>): Prisma.Prisma__FloatingOrderClient<runtime.Types.Result.GetResult<Prisma.$FloatingOrderPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first FloatingOrder that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FloatingOrderFindFirstOrThrowArgs} args - Arguments to find a FloatingOrder
   * @example
   * // Get one FloatingOrder
   * const floatingOrder = await prisma.floatingOrder.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends FloatingOrderFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, FloatingOrderFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__FloatingOrderClient<runtime.Types.Result.GetResult<Prisma.$FloatingOrderPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more FloatingOrders that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FloatingOrderFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all FloatingOrders
   * const floatingOrders = await prisma.floatingOrder.findMany()
   * 
   * // Get first 10 FloatingOrders
   * const floatingOrders = await prisma.floatingOrder.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const floatingOrderWithIdOnly = await prisma.floatingOrder.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends FloatingOrderFindManyArgs>(args?: Prisma.SelectSubset<T, FloatingOrderFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$FloatingOrderPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a FloatingOrder.
   * @param {FloatingOrderCreateArgs} args - Arguments to create a FloatingOrder.
   * @example
   * // Create one FloatingOrder
   * const FloatingOrder = await prisma.floatingOrder.create({
   *   data: {
   *     // ... data to create a FloatingOrder
   *   }
   * })
   * 
   */
  create<T extends FloatingOrderCreateArgs>(args: Prisma.SelectSubset<T, FloatingOrderCreateArgs<ExtArgs>>): Prisma.Prisma__FloatingOrderClient<runtime.Types.Result.GetResult<Prisma.$FloatingOrderPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many FloatingOrders.
   * @param {FloatingOrderCreateManyArgs} args - Arguments to create many FloatingOrders.
   * @example
   * // Create many FloatingOrders
   * const floatingOrder = await prisma.floatingOrder.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends FloatingOrderCreateManyArgs>(args?: Prisma.SelectSubset<T, FloatingOrderCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many FloatingOrders and returns the data saved in the database.
   * @param {FloatingOrderCreateManyAndReturnArgs} args - Arguments to create many FloatingOrders.
   * @example
   * // Create many FloatingOrders
   * const floatingOrder = await prisma.floatingOrder.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many FloatingOrders and only return the `id`
   * const floatingOrderWithIdOnly = await prisma.floatingOrder.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends FloatingOrderCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, FloatingOrderCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$FloatingOrderPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a FloatingOrder.
   * @param {FloatingOrderDeleteArgs} args - Arguments to delete one FloatingOrder.
   * @example
   * // Delete one FloatingOrder
   * const FloatingOrder = await prisma.floatingOrder.delete({
   *   where: {
   *     // ... filter to delete one FloatingOrder
   *   }
   * })
   * 
   */
  delete<T extends FloatingOrderDeleteArgs>(args: Prisma.SelectSubset<T, FloatingOrderDeleteArgs<ExtArgs>>): Prisma.Prisma__FloatingOrderClient<runtime.Types.Result.GetResult<Prisma.$FloatingOrderPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one FloatingOrder.
   * @param {FloatingOrderUpdateArgs} args - Arguments to update one FloatingOrder.
   * @example
   * // Update one FloatingOrder
   * const floatingOrder = await prisma.floatingOrder.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends FloatingOrderUpdateArgs>(args: Prisma.SelectSubset<T, FloatingOrderUpdateArgs<ExtArgs>>): Prisma.Prisma__FloatingOrderClient<runtime.Types.Result.GetResult<Prisma.$FloatingOrderPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more FloatingOrders.
   * @param {FloatingOrderDeleteManyArgs} args - Arguments to filter FloatingOrders to delete.
   * @example
   * // Delete a few FloatingOrders
   * const { count } = await prisma.floatingOrder.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends FloatingOrderDeleteManyArgs>(args?: Prisma.SelectSubset<T, FloatingOrderDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more FloatingOrders.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FloatingOrderUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many FloatingOrders
   * const floatingOrder = await prisma.floatingOrder.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends FloatingOrderUpdateManyArgs>(args: Prisma.SelectSubset<T, FloatingOrderUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more FloatingOrders and returns the data updated in the database.
   * @param {FloatingOrderUpdateManyAndReturnArgs} args - Arguments to update many FloatingOrders.
   * @example
   * // Update many FloatingOrders
   * const floatingOrder = await prisma.floatingOrder.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more FloatingOrders and only return the `id`
   * const floatingOrderWithIdOnly = await prisma.floatingOrder.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends FloatingOrderUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, FloatingOrderUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$FloatingOrderPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one FloatingOrder.
   * @param {FloatingOrderUpsertArgs} args - Arguments to update or create a FloatingOrder.
   * @example
   * // Update or create a FloatingOrder
   * const floatingOrder = await prisma.floatingOrder.upsert({
   *   create: {
   *     // ... data to create a FloatingOrder
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the FloatingOrder we want to update
   *   }
   * })
   */
  upsert<T extends FloatingOrderUpsertArgs>(args: Prisma.SelectSubset<T, FloatingOrderUpsertArgs<ExtArgs>>): Prisma.Prisma__FloatingOrderClient<runtime.Types.Result.GetResult<Prisma.$FloatingOrderPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of FloatingOrders.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FloatingOrderCountArgs} args - Arguments to filter FloatingOrders to count.
   * @example
   * // Count the number of FloatingOrders
   * const count = await prisma.floatingOrder.count({
   *   where: {
   *     // ... the filter for the FloatingOrders we want to count
   *   }
   * })
  **/
  count<T extends FloatingOrderCountArgs>(
    args?: Prisma.Subset<T, FloatingOrderCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], FloatingOrderCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a FloatingOrder.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FloatingOrderAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends FloatingOrderAggregateArgs>(args: Prisma.Subset<T, FloatingOrderAggregateArgs>): Prisma.PrismaPromise<GetFloatingOrderAggregateType<T>>

  /**
   * Group by FloatingOrder.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FloatingOrderGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends FloatingOrderGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: FloatingOrderGroupByArgs['orderBy'] }
      : { orderBy?: FloatingOrderGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, FloatingOrderGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetFloatingOrderGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the FloatingOrder model
 */
readonly fields: FloatingOrderFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for FloatingOrder.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__FloatingOrderClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  items<T extends Prisma.FloatingOrder$itemsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.FloatingOrder$itemsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$OrderItemPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the FloatingOrder model
 */
export interface FloatingOrderFieldRefs {
  readonly id: Prisma.FieldRef<"FloatingOrder", 'Int'>
  readonly lastKeepAlive: Prisma.FieldRef<"FloatingOrder", 'DateTime'>
}
    

// Custom InputTypes
/**
 * FloatingOrder findUnique
 */
export type FloatingOrderFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FloatingOrder
   */
  select?: Prisma.FloatingOrderSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FloatingOrder
   */
  omit?: Prisma.FloatingOrderOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FloatingOrderInclude<ExtArgs> | null
  /**
   * Filter, which FloatingOrder to fetch.
   */
  where: Prisma.FloatingOrderWhereUniqueInput
}

/**
 * FloatingOrder findUniqueOrThrow
 */
export type FloatingOrderFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FloatingOrder
   */
  select?: Prisma.FloatingOrderSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FloatingOrder
   */
  omit?: Prisma.FloatingOrderOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FloatingOrderInclude<ExtArgs> | null
  /**
   * Filter, which FloatingOrder to fetch.
   */
  where: Prisma.FloatingOrderWhereUniqueInput
}

/**
 * FloatingOrder findFirst
 */
export type FloatingOrderFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FloatingOrder
   */
  select?: Prisma.FloatingOrderSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FloatingOrder
   */
  omit?: Prisma.FloatingOrderOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FloatingOrderInclude<ExtArgs> | null
  /**
   * Filter, which FloatingOrder to fetch.
   */
  where?: Prisma.FloatingOrderWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of FloatingOrders to fetch.
   */
  orderBy?: Prisma.FloatingOrderOrderByWithRelationInput | Prisma.FloatingOrderOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for FloatingOrders.
   */
  cursor?: Prisma.FloatingOrderWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` FloatingOrders from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` FloatingOrders.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of FloatingOrders.
   */
  distinct?: Prisma.FloatingOrderScalarFieldEnum | Prisma.FloatingOrderScalarFieldEnum[]
}

/**
 * FloatingOrder findFirstOrThrow
 */
export type FloatingOrderFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FloatingOrder
   */
  select?: Prisma.FloatingOrderSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FloatingOrder
   */
  omit?: Prisma.FloatingOrderOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FloatingOrderInclude<ExtArgs> | null
  /**
   * Filter, which FloatingOrder to fetch.
   */
  where?: Prisma.FloatingOrderWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of FloatingOrders to fetch.
   */
  orderBy?: Prisma.FloatingOrderOrderByWithRelationInput | Prisma.FloatingOrderOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for FloatingOrders.
   */
  cursor?: Prisma.FloatingOrderWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` FloatingOrders from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` FloatingOrders.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of FloatingOrders.
   */
  distinct?: Prisma.FloatingOrderScalarFieldEnum | Prisma.FloatingOrderScalarFieldEnum[]
}

/**
 * FloatingOrder findMany
 */
export type FloatingOrderFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FloatingOrder
   */
  select?: Prisma.FloatingOrderSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FloatingOrder
   */
  omit?: Prisma.FloatingOrderOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FloatingOrderInclude<ExtArgs> | null
  /**
   * Filter, which FloatingOrders to fetch.
   */
  where?: Prisma.FloatingOrderWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of FloatingOrders to fetch.
   */
  orderBy?: Prisma.FloatingOrderOrderByWithRelationInput | Prisma.FloatingOrderOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing FloatingOrders.
   */
  cursor?: Prisma.FloatingOrderWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` FloatingOrders from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` FloatingOrders.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of FloatingOrders.
   */
  distinct?: Prisma.FloatingOrderScalarFieldEnum | Prisma.FloatingOrderScalarFieldEnum[]
}

/**
 * FloatingOrder create
 */
export type FloatingOrderCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FloatingOrder
   */
  select?: Prisma.FloatingOrderSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FloatingOrder
   */
  omit?: Prisma.FloatingOrderOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FloatingOrderInclude<ExtArgs> | null
  /**
   * The data needed to create a FloatingOrder.
   */
  data?: Prisma.XOR<Prisma.FloatingOrderCreateInput, Prisma.FloatingOrderUncheckedCreateInput>
}

/**
 * FloatingOrder createMany
 */
export type FloatingOrderCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many FloatingOrders.
   */
  data: Prisma.FloatingOrderCreateManyInput | Prisma.FloatingOrderCreateManyInput[]
}

/**
 * FloatingOrder createManyAndReturn
 */
export type FloatingOrderCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FloatingOrder
   */
  select?: Prisma.FloatingOrderSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the FloatingOrder
   */
  omit?: Prisma.FloatingOrderOmit<ExtArgs> | null
  /**
   * The data used to create many FloatingOrders.
   */
  data: Prisma.FloatingOrderCreateManyInput | Prisma.FloatingOrderCreateManyInput[]
}

/**
 * FloatingOrder update
 */
export type FloatingOrderUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FloatingOrder
   */
  select?: Prisma.FloatingOrderSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FloatingOrder
   */
  omit?: Prisma.FloatingOrderOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FloatingOrderInclude<ExtArgs> | null
  /**
   * The data needed to update a FloatingOrder.
   */
  data: Prisma.XOR<Prisma.FloatingOrderUpdateInput, Prisma.FloatingOrderUncheckedUpdateInput>
  /**
   * Choose, which FloatingOrder to update.
   */
  where: Prisma.FloatingOrderWhereUniqueInput
}

/**
 * FloatingOrder updateMany
 */
export type FloatingOrderUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update FloatingOrders.
   */
  data: Prisma.XOR<Prisma.FloatingOrderUpdateManyMutationInput, Prisma.FloatingOrderUncheckedUpdateManyInput>
  /**
   * Filter which FloatingOrders to update
   */
  where?: Prisma.FloatingOrderWhereInput
  /**
   * Limit how many FloatingOrders to update.
   */
  limit?: number
}

/**
 * FloatingOrder updateManyAndReturn
 */
export type FloatingOrderUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FloatingOrder
   */
  select?: Prisma.FloatingOrderSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the FloatingOrder
   */
  omit?: Prisma.FloatingOrderOmit<ExtArgs> | null
  /**
   * The data used to update FloatingOrders.
   */
  data: Prisma.XOR<Prisma.FloatingOrderUpdateManyMutationInput, Prisma.FloatingOrderUncheckedUpdateManyInput>
  /**
   * Filter which FloatingOrders to update
   */
  where?: Prisma.FloatingOrderWhereInput
  /**
   * Limit how many FloatingOrders to update.
   */
  limit?: number
}

/**
 * FloatingOrder upsert
 */
export type FloatingOrderUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FloatingOrder
   */
  select?: Prisma.FloatingOrderSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FloatingOrder
   */
  omit?: Prisma.FloatingOrderOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FloatingOrderInclude<ExtArgs> | null
  /**
   * The filter to search for the FloatingOrder to update in case it exists.
   */
  where: Prisma.FloatingOrderWhereUniqueInput
  /**
   * In case the FloatingOrder found by the `where` argument doesn't exist, create a new FloatingOrder with this data.
   */
  create: Prisma.XOR<Prisma.FloatingOrderCreateInput, Prisma.FloatingOrderUncheckedCreateInput>
  /**
   * In case the FloatingOrder was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.FloatingOrderUpdateInput, Prisma.FloatingOrderUncheckedUpdateInput>
}

/**
 * FloatingOrder delete
 */
export type FloatingOrderDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FloatingOrder
   */
  select?: Prisma.FloatingOrderSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FloatingOrder
   */
  omit?: Prisma.FloatingOrderOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FloatingOrderInclude<ExtArgs> | null
  /**
   * Filter which FloatingOrder to delete.
   */
  where: Prisma.FloatingOrderWhereUniqueInput
}

/**
 * FloatingOrder deleteMany
 */
export type FloatingOrderDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which FloatingOrders to delete
   */
  where?: Prisma.FloatingOrderWhereInput
  /**
   * Limit how many FloatingOrders to delete.
   */
  limit?: number
}

/**
 * FloatingOrder.items
 */
export type FloatingOrder$itemsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OrderItem
   */
  select?: Prisma.OrderItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OrderItem
   */
  omit?: Prisma.OrderItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OrderItemInclude<ExtArgs> | null
  where?: Prisma.OrderItemWhereInput
  orderBy?: Prisma.OrderItemOrderByWithRelationInput | Prisma.OrderItemOrderByWithRelationInput[]
  cursor?: Prisma.OrderItemWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.OrderItemScalarFieldEnum | Prisma.OrderItemScalarFieldEnum[]
}

/**
 * FloatingOrder without action
 */
export type FloatingOrderDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FloatingOrder
   */
  select?: Prisma.FloatingOrderSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FloatingOrder
   */
  omit?: Prisma.FloatingOrderOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FloatingOrderInclude<ExtArgs> | null
}
