
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `SumUpPayment` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model SumUpPayment
 * 
 */
export type SumUpPaymentModel = runtime.Types.Result.DefaultSelection<Prisma.$SumUpPaymentPayload>

export type AggregateSumUpPayment = {
  _count: SumUpPaymentCountAggregateOutputType | null
  _avg: SumUpPaymentAvgAggregateOutputType | null
  _sum: SumUpPaymentSumAggregateOutputType | null
  _min: SumUpPaymentMinAggregateOutputType | null
  _max: SumUpPaymentMaxAggregateOutputType | null
}

export type SumUpPaymentAvgAggregateOutputType = {
  id: number | null
  amount: number | null
  orderId: number | null
}

export type SumUpPaymentSumAggregateOutputType = {
  id: number | null
  amount: number | null
  orderId: number | null
}

export type SumUpPaymentMinAggregateOutputType = {
  id: number | null
  paymentId: string | null
  status: $Enums.PaymentStatus | null
  amount: number | null
  orderId: number | null
}

export type SumUpPaymentMaxAggregateOutputType = {
  id: number | null
  paymentId: string | null
  status: $Enums.PaymentStatus | null
  amount: number | null
  orderId: number | null
}

export type SumUpPaymentCountAggregateOutputType = {
  id: number
  paymentId: number
  status: number
  amount: number
  orderId: number
  _all: number
}


export type SumUpPaymentAvgAggregateInputType = {
  id?: true
  amount?: true
  orderId?: true
}

export type SumUpPaymentSumAggregateInputType = {
  id?: true
  amount?: true
  orderId?: true
}

export type SumUpPaymentMinAggregateInputType = {
  id?: true
  paymentId?: true
  status?: true
  amount?: true
  orderId?: true
}

export type SumUpPaymentMaxAggregateInputType = {
  id?: true
  paymentId?: true
  status?: true
  amount?: true
  orderId?: true
}

export type SumUpPaymentCountAggregateInputType = {
  id?: true
  paymentId?: true
  status?: true
  amount?: true
  orderId?: true
  _all?: true
}

export type SumUpPaymentAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which SumUpPayment to aggregate.
   */
  where?: Prisma.SumUpPaymentWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SumUpPayments to fetch.
   */
  orderBy?: Prisma.SumUpPaymentOrderByWithRelationInput | Prisma.SumUpPaymentOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.SumUpPaymentWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SumUpPayments from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SumUpPayments.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned SumUpPayments
  **/
  _count?: true | SumUpPaymentCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: SumUpPaymentAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: SumUpPaymentSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: SumUpPaymentMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: SumUpPaymentMaxAggregateInputType
}

export type GetSumUpPaymentAggregateType<T extends SumUpPaymentAggregateArgs> = {
      [P in keyof T & keyof AggregateSumUpPayment]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateSumUpPayment[P]>
    : Prisma.GetScalarType<T[P], AggregateSumUpPayment[P]>
}




export type SumUpPaymentGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.SumUpPaymentWhereInput
  orderBy?: Prisma.SumUpPaymentOrderByWithAggregationInput | Prisma.SumUpPaymentOrderByWithAggregationInput[]
  by: Prisma.SumUpPaymentScalarFieldEnum[] | Prisma.SumUpPaymentScalarFieldEnum
  having?: Prisma.SumUpPaymentScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: SumUpPaymentCountAggregateInputType | true
  _avg?: SumUpPaymentAvgAggregateInputType
  _sum?: SumUpPaymentSumAggregateInputType
  _min?: SumUpPaymentMinAggregateInputType
  _max?: SumUpPaymentMaxAggregateInputType
}

export type SumUpPaymentGroupByOutputType = {
  id: number
  paymentId: string | null
  status: $Enums.PaymentStatus
  amount: number
  orderId: number | null
  _count: SumUpPaymentCountAggregateOutputType | null
  _avg: SumUpPaymentAvgAggregateOutputType | null
  _sum: SumUpPaymentSumAggregateOutputType | null
  _min: SumUpPaymentMinAggregateOutputType | null
  _max: SumUpPaymentMaxAggregateOutputType | null
}

export type GetSumUpPaymentGroupByPayload<T extends SumUpPaymentGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<SumUpPaymentGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof SumUpPaymentGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], SumUpPaymentGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], SumUpPaymentGroupByOutputType[P]>
      }
    >
  >



export type SumUpPaymentWhereInput = {
  AND?: Prisma.SumUpPaymentWhereInput | Prisma.SumUpPaymentWhereInput[]
  OR?: Prisma.SumUpPaymentWhereInput[]
  NOT?: Prisma.SumUpPaymentWhereInput | Prisma.SumUpPaymentWhereInput[]
  id?: Prisma.IntFilter<"SumUpPayment"> | number
  paymentId?: Prisma.StringNullableFilter<"SumUpPayment"> | string | null
  status?: Prisma.EnumPaymentStatusFilter<"SumUpPayment"> | $Enums.PaymentStatus
  amount?: Prisma.IntFilter<"SumUpPayment"> | number
  orderId?: Prisma.IntNullableFilter<"SumUpPayment"> | number | null
  order?: Prisma.XOR<Prisma.OrderNullableScalarRelationFilter, Prisma.OrderWhereInput> | null
}

export type SumUpPaymentOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  paymentId?: Prisma.SortOrderInput | Prisma.SortOrder
  status?: Prisma.SortOrder
  amount?: Prisma.SortOrder
  orderId?: Prisma.SortOrderInput | Prisma.SortOrder
  order?: Prisma.OrderOrderByWithRelationInput
}

export type SumUpPaymentWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  AND?: Prisma.SumUpPaymentWhereInput | Prisma.SumUpPaymentWhereInput[]
  OR?: Prisma.SumUpPaymentWhereInput[]
  NOT?: Prisma.SumUpPaymentWhereInput | Prisma.SumUpPaymentWhereInput[]
  paymentId?: Prisma.StringNullableFilter<"SumUpPayment"> | string | null
  status?: Prisma.EnumPaymentStatusFilter<"SumUpPayment"> | $Enums.PaymentStatus
  amount?: Prisma.IntFilter<"SumUpPayment"> | number
  orderId?: Prisma.IntNullableFilter<"SumUpPayment"> | number | null
  order?: Prisma.XOR<Prisma.OrderNullableScalarRelationFilter, Prisma.OrderWhereInput> | null
}, "id">

export type SumUpPaymentOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  paymentId?: Prisma.SortOrderInput | Prisma.SortOrder
  status?: Prisma.SortOrder
  amount?: Prisma.SortOrder
  orderId?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.SumUpPaymentCountOrderByAggregateInput
  _avg?: Prisma.SumUpPaymentAvgOrderByAggregateInput
  _max?: Prisma.SumUpPaymentMaxOrderByAggregateInput
  _min?: Prisma.SumUpPaymentMinOrderByAggregateInput
  _sum?: Prisma.SumUpPaymentSumOrderByAggregateInput
}

export type SumUpPaymentScalarWhereWithAggregatesInput = {
  AND?: Prisma.SumUpPaymentScalarWhereWithAggregatesInput | Prisma.SumUpPaymentScalarWhereWithAggregatesInput[]
  OR?: Prisma.SumUpPaymentScalarWhereWithAggregatesInput[]
  NOT?: Prisma.SumUpPaymentScalarWhereWithAggregatesInput | Prisma.SumUpPaymentScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"SumUpPayment"> | number
  paymentId?: Prisma.StringNullableWithAggregatesFilter<"SumUpPayment"> | string | null
  status?: Prisma.EnumPaymentStatusWithAggregatesFilter<"SumUpPayment"> | $Enums.PaymentStatus
  amount?: Prisma.IntWithAggregatesFilter<"SumUpPayment"> | number
  orderId?: Prisma.IntNullableWithAggregatesFilter<"SumUpPayment"> | number | null
}

export type SumUpPaymentCreateInput = {
  paymentId?: string | null
  status: $Enums.PaymentStatus
  amount: number
  order?: Prisma.OrderCreateNestedOneWithoutSumUpPaymentsInput
}

export type SumUpPaymentUncheckedCreateInput = {
  id?: number
  paymentId?: string | null
  status: $Enums.PaymentStatus
  amount: number
  orderId?: number | null
}

export type SumUpPaymentUpdateInput = {
  paymentId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.EnumPaymentStatusFieldUpdateOperationsInput | $Enums.PaymentStatus
  amount?: Prisma.IntFieldUpdateOperationsInput | number
  order?: Prisma.OrderUpdateOneWithoutSumUpPaymentsNestedInput
}

export type SumUpPaymentUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  paymentId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.EnumPaymentStatusFieldUpdateOperationsInput | $Enums.PaymentStatus
  amount?: Prisma.IntFieldUpdateOperationsInput | number
  orderId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
}

export type SumUpPaymentCreateManyInput = {
  id?: number
  paymentId?: string | null
  status: $Enums.PaymentStatus
  amount: number
  orderId?: number | null
}

export type SumUpPaymentUpdateManyMutationInput = {
  paymentId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.EnumPaymentStatusFieldUpdateOperationsInput | $Enums.PaymentStatus
  amount?: Prisma.IntFieldUpdateOperationsInput | number
}

export type SumUpPaymentUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  paymentId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.EnumPaymentStatusFieldUpdateOperationsInput | $Enums.PaymentStatus
  amount?: Prisma.IntFieldUpdateOperationsInput | number
  orderId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
}

export type SumUpPaymentListRelationFilter = {
  every?: Prisma.SumUpPaymentWhereInput
  some?: Prisma.SumUpPaymentWhereInput
  none?: Prisma.SumUpPaymentWhereInput
}

export type SumUpPaymentOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type SumUpPaymentCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  paymentId?: Prisma.SortOrder
  status?: Prisma.SortOrder
  amount?: Prisma.SortOrder
  orderId?: Prisma.SortOrder
}

export type SumUpPaymentAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  amount?: Prisma.SortOrder
  orderId?: Prisma.SortOrder
}

export type SumUpPaymentMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  paymentId?: Prisma.SortOrder
  status?: Prisma.SortOrder
  amount?: Prisma.SortOrder
  orderId?: Prisma.SortOrder
}

export type SumUpPaymentMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  paymentId?: Prisma.SortOrder
  status?: Prisma.SortOrder
  amount?: Prisma.SortOrder
  orderId?: Prisma.SortOrder
}

export type SumUpPaymentSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  amount?: Prisma.SortOrder
  orderId?: Prisma.SortOrder
}

export type SumUpPaymentCreateNestedManyWithoutOrderInput = {
  create?: Prisma.XOR<Prisma.SumUpPaymentCreateWithoutOrderInput, Prisma.SumUpPaymentUncheckedCreateWithoutOrderInput> | Prisma.SumUpPaymentCreateWithoutOrderInput[] | Prisma.SumUpPaymentUncheckedCreateWithoutOrderInput[]
  connectOrCreate?: Prisma.SumUpPaymentCreateOrConnectWithoutOrderInput | Prisma.SumUpPaymentCreateOrConnectWithoutOrderInput[]
  createMany?: Prisma.SumUpPaymentCreateManyOrderInputEnvelope
  connect?: Prisma.SumUpPaymentWhereUniqueInput | Prisma.SumUpPaymentWhereUniqueInput[]
}

export type SumUpPaymentUncheckedCreateNestedManyWithoutOrderInput = {
  create?: Prisma.XOR<Prisma.SumUpPaymentCreateWithoutOrderInput, Prisma.SumUpPaymentUncheckedCreateWithoutOrderInput> | Prisma.SumUpPaymentCreateWithoutOrderInput[] | Prisma.SumUpPaymentUncheckedCreateWithoutOrderInput[]
  connectOrCreate?: Prisma.SumUpPaymentCreateOrConnectWithoutOrderInput | Prisma.SumUpPaymentCreateOrConnectWithoutOrderInput[]
  createMany?: Prisma.SumUpPaymentCreateManyOrderInputEnvelope
  connect?: Prisma.SumUpPaymentWhereUniqueInput | Prisma.SumUpPaymentWhereUniqueInput[]
}

export type SumUpPaymentUpdateManyWithoutOrderNestedInput = {
  create?: Prisma.XOR<Prisma.SumUpPaymentCreateWithoutOrderInput, Prisma.SumUpPaymentUncheckedCreateWithoutOrderInput> | Prisma.SumUpPaymentCreateWithoutOrderInput[] | Prisma.SumUpPaymentUncheckedCreateWithoutOrderInput[]
  connectOrCreate?: Prisma.SumUpPaymentCreateOrConnectWithoutOrderInput | Prisma.SumUpPaymentCreateOrConnectWithoutOrderInput[]
  upsert?: Prisma.SumUpPaymentUpsertWithWhereUniqueWithoutOrderInput | Prisma.SumUpPaymentUpsertWithWhereUniqueWithoutOrderInput[]
  createMany?: Prisma.SumUpPaymentCreateManyOrderInputEnvelope
  set?: Prisma.SumUpPaymentWhereUniqueInput | Prisma.SumUpPaymentWhereUniqueInput[]
  disconnect?: Prisma.SumUpPaymentWhereUniqueInput | Prisma.SumUpPaymentWhereUniqueInput[]
  delete?: Prisma.SumUpPaymentWhereUniqueInput | Prisma.SumUpPaymentWhereUniqueInput[]
  connect?: Prisma.SumUpPaymentWhereUniqueInput | Prisma.SumUpPaymentWhereUniqueInput[]
  update?: Prisma.SumUpPaymentUpdateWithWhereUniqueWithoutOrderInput | Prisma.SumUpPaymentUpdateWithWhereUniqueWithoutOrderInput[]
  updateMany?: Prisma.SumUpPaymentUpdateManyWithWhereWithoutOrderInput | Prisma.SumUpPaymentUpdateManyWithWhereWithoutOrderInput[]
  deleteMany?: Prisma.SumUpPaymentScalarWhereInput | Prisma.SumUpPaymentScalarWhereInput[]
}

export type SumUpPaymentUncheckedUpdateManyWithoutOrderNestedInput = {
  create?: Prisma.XOR<Prisma.SumUpPaymentCreateWithoutOrderInput, Prisma.SumUpPaymentUncheckedCreateWithoutOrderInput> | Prisma.SumUpPaymentCreateWithoutOrderInput[] | Prisma.SumUpPaymentUncheckedCreateWithoutOrderInput[]
  connectOrCreate?: Prisma.SumUpPaymentCreateOrConnectWithoutOrderInput | Prisma.SumUpPaymentCreateOrConnectWithoutOrderInput[]
  upsert?: Prisma.SumUpPaymentUpsertWithWhereUniqueWithoutOrderInput | Prisma.SumUpPaymentUpsertWithWhereUniqueWithoutOrderInput[]
  createMany?: Prisma.SumUpPaymentCreateManyOrderInputEnvelope
  set?: Prisma.SumUpPaymentWhereUniqueInput | Prisma.SumUpPaymentWhereUniqueInput[]
  disconnect?: Prisma.SumUpPaymentWhereUniqueInput | Prisma.SumUpPaymentWhereUniqueInput[]
  delete?: Prisma.SumUpPaymentWhereUniqueInput | Prisma.SumUpPaymentWhereUniqueInput[]
  connect?: Prisma.SumUpPaymentWhereUniqueInput | Prisma.SumUpPaymentWhereUniqueInput[]
  update?: Prisma.SumUpPaymentUpdateWithWhereUniqueWithoutOrderInput | Prisma.SumUpPaymentUpdateWithWhereUniqueWithoutOrderInput[]
  updateMany?: Prisma.SumUpPaymentUpdateManyWithWhereWithoutOrderInput | Prisma.SumUpPaymentUpdateManyWithWhereWithoutOrderInput[]
  deleteMany?: Prisma.SumUpPaymentScalarWhereInput | Prisma.SumUpPaymentScalarWhereInput[]
}

export type NullableStringFieldUpdateOperationsInput = {
  set?: string | null
}

export type EnumPaymentStatusFieldUpdateOperationsInput = {
  set?: $Enums.PaymentStatus
}

export type SumUpPaymentCreateWithoutOrderInput = {
  paymentId?: string | null
  status: $Enums.PaymentStatus
  amount: number
}

export type SumUpPaymentUncheckedCreateWithoutOrderInput = {
  id?: number
  paymentId?: string | null
  status: $Enums.PaymentStatus
  amount: number
}

export type SumUpPaymentCreateOrConnectWithoutOrderInput = {
  where: Prisma.SumUpPaymentWhereUniqueInput
  create: Prisma.XOR<Prisma.SumUpPaymentCreateWithoutOrderInput, Prisma.SumUpPaymentUncheckedCreateWithoutOrderInput>
}

export type SumUpPaymentCreateManyOrderInputEnvelope = {
  data: Prisma.SumUpPaymentCreateManyOrderInput | Prisma.SumUpPaymentCreateManyOrderInput[]
}

export type SumUpPaymentUpsertWithWhereUniqueWithoutOrderInput = {
  where: Prisma.SumUpPaymentWhereUniqueInput
  update: Prisma.XOR<Prisma.SumUpPaymentUpdateWithoutOrderInput, Prisma.SumUpPaymentUncheckedUpdateWithoutOrderInput>
  create: Prisma.XOR<Prisma.SumUpPaymentCreateWithoutOrderInput, Prisma.SumUpPaymentUncheckedCreateWithoutOrderInput>
}

export type SumUpPaymentUpdateWithWhereUniqueWithoutOrderInput = {
  where: Prisma.SumUpPaymentWhereUniqueInput
  data: Prisma.XOR<Prisma.SumUpPaymentUpdateWithoutOrderInput, Prisma.SumUpPaymentUncheckedUpdateWithoutOrderInput>
}

export type SumUpPaymentUpdateManyWithWhereWithoutOrderInput = {
  where: Prisma.SumUpPaymentScalarWhereInput
  data: Prisma.XOR<Prisma.SumUpPaymentUpdateManyMutationInput, Prisma.SumUpPaymentUncheckedUpdateManyWithoutOrderInput>
}

export type SumUpPaymentScalarWhereInput = {
  AND?: Prisma.SumUpPaymentScalarWhereInput | Prisma.SumUpPaymentScalarWhereInput[]
  OR?: Prisma.SumUpPaymentScalarWhereInput[]
  NOT?: Prisma.SumUpPaymentScalarWhereInput | Prisma.SumUpPaymentScalarWhereInput[]
  id?: Prisma.IntFilter<"SumUpPayment"> | number
  paymentId?: Prisma.StringNullableFilter<"SumUpPayment"> | string | null
  status?: Prisma.EnumPaymentStatusFilter<"SumUpPayment"> | $Enums.PaymentStatus
  amount?: Prisma.IntFilter<"SumUpPayment"> | number
  orderId?: Prisma.IntNullableFilter<"SumUpPayment"> | number | null
}

export type SumUpPaymentCreateManyOrderInput = {
  id?: number
  paymentId?: string | null
  status: $Enums.PaymentStatus
  amount: number
}

export type SumUpPaymentUpdateWithoutOrderInput = {
  paymentId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.EnumPaymentStatusFieldUpdateOperationsInput | $Enums.PaymentStatus
  amount?: Prisma.IntFieldUpdateOperationsInput | number
}

export type SumUpPaymentUncheckedUpdateWithoutOrderInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  paymentId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.EnumPaymentStatusFieldUpdateOperationsInput | $Enums.PaymentStatus
  amount?: Prisma.IntFieldUpdateOperationsInput | number
}

export type SumUpPaymentUncheckedUpdateManyWithoutOrderInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  paymentId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.EnumPaymentStatusFieldUpdateOperationsInput | $Enums.PaymentStatus
  amount?: Prisma.IntFieldUpdateOperationsInput | number
}



export type SumUpPaymentSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  paymentId?: boolean
  status?: boolean
  amount?: boolean
  orderId?: boolean
  order?: boolean | Prisma.SumUpPayment$orderArgs<ExtArgs>
}, ExtArgs["result"]["sumUpPayment"]>

export type SumUpPaymentSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  paymentId?: boolean
  status?: boolean
  amount?: boolean
  orderId?: boolean
  order?: boolean | Prisma.SumUpPayment$orderArgs<ExtArgs>
}, ExtArgs["result"]["sumUpPayment"]>

export type SumUpPaymentSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  paymentId?: boolean
  status?: boolean
  amount?: boolean
  orderId?: boolean
  order?: boolean | Prisma.SumUpPayment$orderArgs<ExtArgs>
}, ExtArgs["result"]["sumUpPayment"]>

export type SumUpPaymentSelectScalar = {
  id?: boolean
  paymentId?: boolean
  status?: boolean
  amount?: boolean
  orderId?: boolean
}

export type SumUpPaymentOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "paymentId" | "status" | "amount" | "orderId", ExtArgs["result"]["sumUpPayment"]>
export type SumUpPaymentInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  order?: boolean | Prisma.SumUpPayment$orderArgs<ExtArgs>
}
export type SumUpPaymentIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  order?: boolean | Prisma.SumUpPayment$orderArgs<ExtArgs>
}
export type SumUpPaymentIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  order?: boolean | Prisma.SumUpPayment$orderArgs<ExtArgs>
}

export type $SumUpPaymentPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "SumUpPayment"
  objects: {
    order: Prisma.$OrderPayload<ExtArgs> | null
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    paymentId: string | null
    status: $Enums.PaymentStatus
    amount: number
    orderId: number | null
  }, ExtArgs["result"]["sumUpPayment"]>
  composites: {}
}

export type SumUpPaymentGetPayload<S extends boolean | null | undefined | SumUpPaymentDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$SumUpPaymentPayload, S>

export type SumUpPaymentCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<SumUpPaymentFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: SumUpPaymentCountAggregateInputType | true
  }

export interface SumUpPaymentDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['SumUpPayment'], meta: { name: 'SumUpPayment' } }
  /**
   * Find zero or one SumUpPayment that matches the filter.
   * @param {SumUpPaymentFindUniqueArgs} args - Arguments to find a SumUpPayment
   * @example
   * // Get one SumUpPayment
   * const sumUpPayment = await prisma.sumUpPayment.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends SumUpPaymentFindUniqueArgs>(args: Prisma.SelectSubset<T, SumUpPaymentFindUniqueArgs<ExtArgs>>): Prisma.Prisma__SumUpPaymentClient<runtime.Types.Result.GetResult<Prisma.$SumUpPaymentPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one SumUpPayment that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {SumUpPaymentFindUniqueOrThrowArgs} args - Arguments to find a SumUpPayment
   * @example
   * // Get one SumUpPayment
   * const sumUpPayment = await prisma.sumUpPayment.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends SumUpPaymentFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, SumUpPaymentFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__SumUpPaymentClient<runtime.Types.Result.GetResult<Prisma.$SumUpPaymentPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first SumUpPayment that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SumUpPaymentFindFirstArgs} args - Arguments to find a SumUpPayment
   * @example
   * // Get one SumUpPayment
   * const sumUpPayment = await prisma.sumUpPayment.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends SumUpPaymentFindFirstArgs>(args?: Prisma.SelectSubset<T, SumUpPaymentFindFirstArgs<ExtArgs>>): Prisma.Prisma__SumUpPaymentClient<runtime.Types.Result.GetResult<Prisma.$SumUpPaymentPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first SumUpPayment that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SumUpPaymentFindFirstOrThrowArgs} args - Arguments to find a SumUpPayment
   * @example
   * // Get one SumUpPayment
   * const sumUpPayment = await prisma.sumUpPayment.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends SumUpPaymentFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, SumUpPaymentFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__SumUpPaymentClient<runtime.Types.Result.GetResult<Prisma.$SumUpPaymentPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more SumUpPayments that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SumUpPaymentFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all SumUpPayments
   * const sumUpPayments = await prisma.sumUpPayment.findMany()
   * 
   * // Get first 10 SumUpPayments
   * const sumUpPayments = await prisma.sumUpPayment.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const sumUpPaymentWithIdOnly = await prisma.sumUpPayment.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends SumUpPaymentFindManyArgs>(args?: Prisma.SelectSubset<T, SumUpPaymentFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SumUpPaymentPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a SumUpPayment.
   * @param {SumUpPaymentCreateArgs} args - Arguments to create a SumUpPayment.
   * @example
   * // Create one SumUpPayment
   * const SumUpPayment = await prisma.sumUpPayment.create({
   *   data: {
   *     // ... data to create a SumUpPayment
   *   }
   * })
   * 
   */
  create<T extends SumUpPaymentCreateArgs>(args: Prisma.SelectSubset<T, SumUpPaymentCreateArgs<ExtArgs>>): Prisma.Prisma__SumUpPaymentClient<runtime.Types.Result.GetResult<Prisma.$SumUpPaymentPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many SumUpPayments.
   * @param {SumUpPaymentCreateManyArgs} args - Arguments to create many SumUpPayments.
   * @example
   * // Create many SumUpPayments
   * const sumUpPayment = await prisma.sumUpPayment.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends SumUpPaymentCreateManyArgs>(args?: Prisma.SelectSubset<T, SumUpPaymentCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many SumUpPayments and returns the data saved in the database.
   * @param {SumUpPaymentCreateManyAndReturnArgs} args - Arguments to create many SumUpPayments.
   * @example
   * // Create many SumUpPayments
   * const sumUpPayment = await prisma.sumUpPayment.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many SumUpPayments and only return the `id`
   * const sumUpPaymentWithIdOnly = await prisma.sumUpPayment.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends SumUpPaymentCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, SumUpPaymentCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SumUpPaymentPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a SumUpPayment.
   * @param {SumUpPaymentDeleteArgs} args - Arguments to delete one SumUpPayment.
   * @example
   * // Delete one SumUpPayment
   * const SumUpPayment = await prisma.sumUpPayment.delete({
   *   where: {
   *     // ... filter to delete one SumUpPayment
   *   }
   * })
   * 
   */
  delete<T extends SumUpPaymentDeleteArgs>(args: Prisma.SelectSubset<T, SumUpPaymentDeleteArgs<ExtArgs>>): Prisma.Prisma__SumUpPaymentClient<runtime.Types.Result.GetResult<Prisma.$SumUpPaymentPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one SumUpPayment.
   * @param {SumUpPaymentUpdateArgs} args - Arguments to update one SumUpPayment.
   * @example
   * // Update one SumUpPayment
   * const sumUpPayment = await prisma.sumUpPayment.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends SumUpPaymentUpdateArgs>(args: Prisma.SelectSubset<T, SumUpPaymentUpdateArgs<ExtArgs>>): Prisma.Prisma__SumUpPaymentClient<runtime.Types.Result.GetResult<Prisma.$SumUpPaymentPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more SumUpPayments.
   * @param {SumUpPaymentDeleteManyArgs} args - Arguments to filter SumUpPayments to delete.
   * @example
   * // Delete a few SumUpPayments
   * const { count } = await prisma.sumUpPayment.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends SumUpPaymentDeleteManyArgs>(args?: Prisma.SelectSubset<T, SumUpPaymentDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more SumUpPayments.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SumUpPaymentUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many SumUpPayments
   * const sumUpPayment = await prisma.sumUpPayment.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends SumUpPaymentUpdateManyArgs>(args: Prisma.SelectSubset<T, SumUpPaymentUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more SumUpPayments and returns the data updated in the database.
   * @param {SumUpPaymentUpdateManyAndReturnArgs} args - Arguments to update many SumUpPayments.
   * @example
   * // Update many SumUpPayments
   * const sumUpPayment = await prisma.sumUpPayment.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more SumUpPayments and only return the `id`
   * const sumUpPaymentWithIdOnly = await prisma.sumUpPayment.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends SumUpPaymentUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, SumUpPaymentUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SumUpPaymentPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one SumUpPayment.
   * @param {SumUpPaymentUpsertArgs} args - Arguments to update or create a SumUpPayment.
   * @example
   * // Update or create a SumUpPayment
   * const sumUpPayment = await prisma.sumUpPayment.upsert({
   *   create: {
   *     // ... data to create a SumUpPayment
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the SumUpPayment we want to update
   *   }
   * })
   */
  upsert<T extends SumUpPaymentUpsertArgs>(args: Prisma.SelectSubset<T, SumUpPaymentUpsertArgs<ExtArgs>>): Prisma.Prisma__SumUpPaymentClient<runtime.Types.Result.GetResult<Prisma.$SumUpPaymentPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of SumUpPayments.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SumUpPaymentCountArgs} args - Arguments to filter SumUpPayments to count.
   * @example
   * // Count the number of SumUpPayments
   * const count = await prisma.sumUpPayment.count({
   *   where: {
   *     // ... the filter for the SumUpPayments we want to count
   *   }
   * })
  **/
  count<T extends SumUpPaymentCountArgs>(
    args?: Prisma.Subset<T, SumUpPaymentCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], SumUpPaymentCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a SumUpPayment.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SumUpPaymentAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends SumUpPaymentAggregateArgs>(args: Prisma.Subset<T, SumUpPaymentAggregateArgs>): Prisma.PrismaPromise<GetSumUpPaymentAggregateType<T>>

  /**
   * Group by SumUpPayment.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SumUpPaymentGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends SumUpPaymentGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: SumUpPaymentGroupByArgs['orderBy'] }
      : { orderBy?: SumUpPaymentGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, SumUpPaymentGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetSumUpPaymentGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the SumUpPayment model
 */
readonly fields: SumUpPaymentFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for SumUpPayment.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__SumUpPaymentClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  order<T extends Prisma.SumUpPayment$orderArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.SumUpPayment$orderArgs<ExtArgs>>): Prisma.Prisma__OrderClient<runtime.Types.Result.GetResult<Prisma.$OrderPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the SumUpPayment model
 */
export interface SumUpPaymentFieldRefs {
  readonly id: Prisma.FieldRef<"SumUpPayment", 'Int'>
  readonly paymentId: Prisma.FieldRef<"SumUpPayment", 'String'>
  readonly status: Prisma.FieldRef<"SumUpPayment", 'PaymentStatus'>
  readonly amount: Prisma.FieldRef<"SumUpPayment", 'Int'>
  readonly orderId: Prisma.FieldRef<"SumUpPayment", 'Int'>
}
    

// Custom InputTypes
/**
 * SumUpPayment findUnique
 */
export type SumUpPaymentFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SumUpPayment
   */
  select?: Prisma.SumUpPaymentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SumUpPayment
   */
  omit?: Prisma.SumUpPaymentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SumUpPaymentInclude<ExtArgs> | null
  /**
   * Filter, which SumUpPayment to fetch.
   */
  where: Prisma.SumUpPaymentWhereUniqueInput
}

/**
 * SumUpPayment findUniqueOrThrow
 */
export type SumUpPaymentFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SumUpPayment
   */
  select?: Prisma.SumUpPaymentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SumUpPayment
   */
  omit?: Prisma.SumUpPaymentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SumUpPaymentInclude<ExtArgs> | null
  /**
   * Filter, which SumUpPayment to fetch.
   */
  where: Prisma.SumUpPaymentWhereUniqueInput
}

/**
 * SumUpPayment findFirst
 */
export type SumUpPaymentFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SumUpPayment
   */
  select?: Prisma.SumUpPaymentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SumUpPayment
   */
  omit?: Prisma.SumUpPaymentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SumUpPaymentInclude<ExtArgs> | null
  /**
   * Filter, which SumUpPayment to fetch.
   */
  where?: Prisma.SumUpPaymentWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SumUpPayments to fetch.
   */
  orderBy?: Prisma.SumUpPaymentOrderByWithRelationInput | Prisma.SumUpPaymentOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for SumUpPayments.
   */
  cursor?: Prisma.SumUpPaymentWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SumUpPayments from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SumUpPayments.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of SumUpPayments.
   */
  distinct?: Prisma.SumUpPaymentScalarFieldEnum | Prisma.SumUpPaymentScalarFieldEnum[]
}

/**
 * SumUpPayment findFirstOrThrow
 */
export type SumUpPaymentFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SumUpPayment
   */
  select?: Prisma.SumUpPaymentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SumUpPayment
   */
  omit?: Prisma.SumUpPaymentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SumUpPaymentInclude<ExtArgs> | null
  /**
   * Filter, which SumUpPayment to fetch.
   */
  where?: Prisma.SumUpPaymentWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SumUpPayments to fetch.
   */
  orderBy?: Prisma.SumUpPaymentOrderByWithRelationInput | Prisma.SumUpPaymentOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for SumUpPayments.
   */
  cursor?: Prisma.SumUpPaymentWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SumUpPayments from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SumUpPayments.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of SumUpPayments.
   */
  distinct?: Prisma.SumUpPaymentScalarFieldEnum | Prisma.SumUpPaymentScalarFieldEnum[]
}

/**
 * SumUpPayment findMany
 */
export type SumUpPaymentFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SumUpPayment
   */
  select?: Prisma.SumUpPaymentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SumUpPayment
   */
  omit?: Prisma.SumUpPaymentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SumUpPaymentInclude<ExtArgs> | null
  /**
   * Filter, which SumUpPayments to fetch.
   */
  where?: Prisma.SumUpPaymentWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SumUpPayments to fetch.
   */
  orderBy?: Prisma.SumUpPaymentOrderByWithRelationInput | Prisma.SumUpPaymentOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing SumUpPayments.
   */
  cursor?: Prisma.SumUpPaymentWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SumUpPayments from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SumUpPayments.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of SumUpPayments.
   */
  distinct?: Prisma.SumUpPaymentScalarFieldEnum | Prisma.SumUpPaymentScalarFieldEnum[]
}

/**
 * SumUpPayment create
 */
export type SumUpPaymentCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SumUpPayment
   */
  select?: Prisma.SumUpPaymentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SumUpPayment
   */
  omit?: Prisma.SumUpPaymentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SumUpPaymentInclude<ExtArgs> | null
  /**
   * The data needed to create a SumUpPayment.
   */
  data: Prisma.XOR<Prisma.SumUpPaymentCreateInput, Prisma.SumUpPaymentUncheckedCreateInput>
}

/**
 * SumUpPayment createMany
 */
export type SumUpPaymentCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many SumUpPayments.
   */
  data: Prisma.SumUpPaymentCreateManyInput | Prisma.SumUpPaymentCreateManyInput[]
}

/**
 * SumUpPayment createManyAndReturn
 */
export type SumUpPaymentCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SumUpPayment
   */
  select?: Prisma.SumUpPaymentSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the SumUpPayment
   */
  omit?: Prisma.SumUpPaymentOmit<ExtArgs> | null
  /**
   * The data used to create many SumUpPayments.
   */
  data: Prisma.SumUpPaymentCreateManyInput | Prisma.SumUpPaymentCreateManyInput[]
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SumUpPaymentIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * SumUpPayment update
 */
export type SumUpPaymentUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SumUpPayment
   */
  select?: Prisma.SumUpPaymentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SumUpPayment
   */
  omit?: Prisma.SumUpPaymentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SumUpPaymentInclude<ExtArgs> | null
  /**
   * The data needed to update a SumUpPayment.
   */
  data: Prisma.XOR<Prisma.SumUpPaymentUpdateInput, Prisma.SumUpPaymentUncheckedUpdateInput>
  /**
   * Choose, which SumUpPayment to update.
   */
  where: Prisma.SumUpPaymentWhereUniqueInput
}

/**
 * SumUpPayment updateMany
 */
export type SumUpPaymentUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update SumUpPayments.
   */
  data: Prisma.XOR<Prisma.SumUpPaymentUpdateManyMutationInput, Prisma.SumUpPaymentUncheckedUpdateManyInput>
  /**
   * Filter which SumUpPayments to update
   */
  where?: Prisma.SumUpPaymentWhereInput
  /**
   * Limit how many SumUpPayments to update.
   */
  limit?: number
}

/**
 * SumUpPayment updateManyAndReturn
 */
export type SumUpPaymentUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SumUpPayment
   */
  select?: Prisma.SumUpPaymentSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the SumUpPayment
   */
  omit?: Prisma.SumUpPaymentOmit<ExtArgs> | null
  /**
   * The data used to update SumUpPayments.
   */
  data: Prisma.XOR<Prisma.SumUpPaymentUpdateManyMutationInput, Prisma.SumUpPaymentUncheckedUpdateManyInput>
  /**
   * Filter which SumUpPayments to update
   */
  where?: Prisma.SumUpPaymentWhereInput
  /**
   * Limit how many SumUpPayments to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SumUpPaymentIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * SumUpPayment upsert
 */
export type SumUpPaymentUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SumUpPayment
   */
  select?: Prisma.SumUpPaymentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SumUpPayment
   */
  omit?: Prisma.SumUpPaymentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SumUpPaymentInclude<ExtArgs> | null
  /**
   * The filter to search for the SumUpPayment to update in case it exists.
   */
  where: Prisma.SumUpPaymentWhereUniqueInput
  /**
   * In case the SumUpPayment found by the `where` argument doesn't exist, create a new SumUpPayment with this data.
   */
  create: Prisma.XOR<Prisma.SumUpPaymentCreateInput, Prisma.SumUpPaymentUncheckedCreateInput>
  /**
   * In case the SumUpPayment was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.SumUpPaymentUpdateInput, Prisma.SumUpPaymentUncheckedUpdateInput>
}

/**
 * SumUpPayment delete
 */
export type SumUpPaymentDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SumUpPayment
   */
  select?: Prisma.SumUpPaymentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SumUpPayment
   */
  omit?: Prisma.SumUpPaymentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SumUpPaymentInclude<ExtArgs> | null
  /**
   * Filter which SumUpPayment to delete.
   */
  where: Prisma.SumUpPaymentWhereUniqueInput
}

/**
 * SumUpPayment deleteMany
 */
export type SumUpPaymentDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which SumUpPayments to delete
   */
  where?: Prisma.SumUpPaymentWhereInput
  /**
   * Limit how many SumUpPayments to delete.
   */
  limit?: number
}

/**
 * SumUpPayment.order
 */
export type SumUpPayment$orderArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Order
   */
  select?: Prisma.OrderSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Order
   */
  omit?: Prisma.OrderOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OrderInclude<ExtArgs> | null
  where?: Prisma.OrderWhereInput
}

/**
 * SumUpPayment without action
 */
export type SumUpPaymentDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SumUpPayment
   */
  select?: Prisma.SumUpPaymentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SumUpPayment
   */
  omit?: Prisma.SumUpPaymentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SumUpPaymentInclude<ExtArgs> | null
}
